# Generated by Django 4.1 on 2022-08-25 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('question_one', models.CharField(max_length=20)),
                ('question_two', models.CharField(max_length=20)),
                ('question_three', models.CharField(max_length=20)),
                ('question_one_count', models.IntegerField(default=0)),
                ('question_two_count', models.IntegerField(default=0)),
                ('question_three_count', models.IntegerField(default=0)),
            ],
        ),
    ]
