# Generated by Django 4.1 on 2022-08-27 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='question_slug',
            field=models.SlugField(default=None),
        ),
    ]
