# Generated by Django 4.1 on 2022-08-27 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_poll_question_one_alter_poll_question_three_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
