# Generated by Django 4.1 on 2022-08-27 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_alter_poll_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='img',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to='vote_img'),
        ),
    ]
