# Generated by Django 4.1 on 2022-08-29 04:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_poll_date_created'),
    ]

    operations = [
        migrations.RenameField(
            model_name='poll',
            old_name='img',
            new_name='poll_img',
        ),
    ]
