# Generated by Django 4.1 on 2022-08-29 04:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_rename_img_poll_poll_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='date_created',
            field=models.DateField(blank=True, default=datetime.datetime.now, null=True),
        ),
    ]
