# Generated by Django 4.1 on 2022-09-02 22:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_profile_user'),
        ('base', '0015_alter_poll_poll_creator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='poll_creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.profile'),
        ),
    ]
