# Generated by Django 4.1 on 2022-09-03 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_alter_poll_poll_creator'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='foo',
            field=models.CharField(default=None, max_length=200),
        ),
    ]
