# Generated by Django 4.1 on 2022-09-03 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0017_poll_foo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poll',
            name='foo',
        ),
    ]
