# Generated by Django 4.1 on 2022-09-04 08:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0018_remove_poll_foo'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='voted',
            field=models.ManyToManyField(null=True, related_name='user_voted', to=settings.AUTH_USER_MODEL),
        ),
    ]
