# Generated by Django 4.1.1 on 2022-09-06 13:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0019_poll_voted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='voted',
            field=models.ManyToManyField(blank=True, null=True, related_name='user_voted', to=settings.AUTH_USER_MODEL),
        ),
    ]
