# Generated by Django 4.1.1 on 2022-09-06 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0020_alter_poll_voted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='question_slug',
            field=models.SlugField(default=None, max_length=65),
        ),
    ]
